name: "Check Safety"
on:
  pull_request:
  push:

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  safety:
    name: J
    runs-on: self-hosted
    timeout-minutes: 1800
    strategy:
      fail-fast: false
      matrix:
        dir: [ 'avx2' ]
        entrypoint: [ 'keypair_derand', 'enc_derand', 'dec' ]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --arg full false --run "echo Dependencies OKâ€¦"
    - run: nix-shell --arg full false --run "make -C code/jasmin/mlkem_${{matrix.dir}}/ ${{matrix.entrypoint}}.safety"
    - uses: actions/upload-artifact@v4
      with:
        name: mlkem_${{matrix.dir}}.${{matrix.entrypoint}}.safety
        path: code/jasmin/mlkem_${{matrix.dir}}/${{matrix.entrypoint}}.safety

