name: "Check Safety"
on:
  pull_request:
  push:

env:
  NIXPKGS_ALLOW_UNFREE: 1
  OCAMLRUNPARAM: b

jobs:
  safety:
    name: J
    runs-on: self-hosted
    timeout-minutes: 3600
    strategy:
      fail-fast: false
      matrix:
        size: [ '1024' ]
        dir: [ 'avx2' ]
        entrypoint: [ 'keypair' ]
    steps:
    - uses: actions/checkout@v4
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --arg full false --run "echo Dependencies OKâ€¦"
    - run: nix-shell --arg full false --run "make -C episode_vi/mlkem/mlkem${{matrix.size}}/${{matrix.dir}}/ ${{matrix.entrypoint}}.safety"
    - uses: actions/upload-artifact@v4
      with:
        name: mlkem_${{matrix.size}}_${{matrix.dir}}.${{matrix.entrypoint}}.safety
        path: episode_vi/mlkem/mlkem${{matrix.size}}/${{matrix.dir}}/${{matrix.entrypoint}}.safety

